# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run pod install, then build the Xcode project"
  lane :build do |options|
    app_store_connect_api_key
    build_app(
      workspace: "Unity-iPhone.xcworkspace",
      scheme: "Unity-iPhone",
      export_method: options[:export_method] || "app-store",
      xcargs: "-allowProvisioningUpdates"
    )
  end

  desc "Push to TestFlight"
  lane :push do
    app_store_connect_api_key
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
  
  desc "Build and Push to TestFlight"
  lane :build_and_push do
    app_store_connect_api_key
    build_app(
      workspace: "Unity-iPhone.xcworkspace",
      scheme: "Unity-iPhone",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates"
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
